environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run lint

build: off
